export const species = [
    { label: 'Cachorro', value: 'cachorro' },
    { label: 'Gato', value: 'gato' },
];

export const dogBreeds = [
    { label: 'Akita', value: 'Akita' },
    { label: 'American Bully', value: 'American Bully' },
    { label: 'Basset', value: 'Basset' },
    { label: 'Beagle', value: 'Beagle' },
    { label: 'Border Collie', value: 'Border Collie' },
    { label: 'Boxer', value: 'Boxer' },
    { label: 'Buldogue', value: 'Buldogue' },
    { label: 'Buldogue Francês', value: 'Buldogue Francês' },
    { label: 'Buldogue Inglês', value: 'Buldogue Inglês' },
    { label: 'Bull Terrier', value: 'Bull Terrier' },
    {
        label: 'Cavalier King Charles Spaniel',
        value: 'Cavalier King Charles Spaniel',
    },
    { label: 'Chihuahua', value: 'Chihuahua' },
    { label: 'Chow-chow', value: 'Chow-chow' },
    { label: 'Cocker Spaniel Americano', value: 'Cocker Spaniel Americano' },
    { label: 'Cocker Spaniel Inglês', value: 'Cocker Spaniel Inglês' },
    { label: 'Dachshund', value: 'Dachshund' },
    { label: 'Dalmata', value: 'Dalmata' },
    { label: 'Dogo Argentino', value: 'Dogo Argentino' },
    { label: 'Dogue Alemão', value: 'Dogue Alemão' },
    { label: 'Dogue Brasileiro', value: 'Dogue Brasileiro' },
    { label: 'Fila Brasileiro', value: 'Fila Brasileiro' },
    { label: 'Fox Terrier', value: 'Fox Terrier' },
    { label: 'Galgo', value: 'Galgo' },
    { label: 'Golden Retriever', value: 'Golden Retriever' },
    { label: 'Husky Siberiano', value: 'Husky Siberiano' },
    { label: 'Labrador', value: 'Labrador' },
    { label: 'Lhasa Apso', value: 'Lhasa Apso' },
    { label: 'Lulu da Pomerânia', value: 'Lulu da Pomerânia' },
    { label: 'Maltês', value: 'Maltês' },
    { label: 'Norfolk Terrier', value: 'Norfolk Terrier' },
    { label: 'Pastor Alemão', value: 'Pastor Alemão' },
    { label: 'Pastor Australiano', value: 'Pastor Australiano' },
    { label: 'Pastor Belga', value: 'Pastor Belga' },
    { label: 'Pastor Belga Malinois', value: 'Pastor Belga Malinois' },
    { label: 'Pastor de Shetland', value: 'Pastor de Shetland' },
    { label: 'Pinscher', value: 'Pinscher' },
    { label: 'Pitbull', value: 'Pitbull' },
    { label: 'Poodle', value: 'Poodle' },
    { label: 'Pug', value: 'Pug' },
    { label: 'Rottweiler', value: 'Rottweiler' },
    { label: 'São Bernardo', value: 'São Bernardo' },
    { label: 'Sem Raça Definida', value: 'Sem Raça Definida' },
    { label: 'Shih-tzu', value: 'Shih-tzu' },
    { label: 'Spitz Alemão', value: 'Spitz Alemão' },
    { label: 'Terrier Brasileiro', value: 'Terrier Brasileiro' },
    { label: 'Terrier Escocês', value: 'Terrier Escocês' },
    { label: 'Yorkshire', value: 'Yorkshire' },
];

export const catBreeds = [
    { label: 'Angorá', value: 'Angorá' },
    { label: 'Ashera', value: 'Ashera' },
    { label: 'Pelo Curto Americano', value: 'Pelo Curto Americano' },
    { label: 'Pelo Curto Brasileiro', value: 'Pelo Curto Brasileiro' },
    { label: 'Pelo Curto Oriental', value: 'Pelo Curto Oriental' },
    { label: 'Persa', value: 'Persa' },
    { label: 'Ragdoll', value: 'Ragdoll' },
    { label: 'Sem Raça Definida', value: 'Sem Raça Definida' },
    { label: 'Siamês', value: 'Siamês' },
];
